apiVersion: v1
kind: Pod
metadata:
  name: newsfeed-webapp
  labels:
    app: newsfeed-webapp
spec:
  containers:
  - image: kkragoth/newsfeed-webapp
    name: newsfeed-webapp
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: secret-volume
      mountPath: "/opt/firebase"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: firebase-secret